/**
 * ShopNest API – generated by openapi-typescript
 * Run `pnpm --filter @shopnest/api-client generate` to regenerate.
 * This file is committed and verified by CI (`git diff --exit-code`).
 *
 * NOTE: This placeholder will be replaced after Commit 3 when the API
 * emits a live OpenAPI spec. The CI gate ensures freshness.
 */

export type paths = Record<string, never>;
export type components = Record<string, never>;
export type operations = Record<string, never>;
